### ISSUE TITLE
MIB Server issue: no mib found

### ISSUE THREAD

**Issue by ivanfr90** [pysnmp/mibs#155] opened 2024-09-16 11:51 UTC
Hi.

We are using the MIB Server image in a K8S environment. Currently we have a problem consisting in that the required MIBs cannot be found in the server. We experienced this issues in other occassions randondly and resolved restarting the pods, but now, we are unable to get it working fine again.

We can see the problem on the **snmp-splunk-connect-for-snmp-worker-trap** pods, where we see the message **"no mib found"**

```
[2024-09-16 11:43:36,353: INFO/MainProcess] Task splunk_connect_for_snmp.snmp.tasks.trap[9added56-4be5-4e98-81dd-59787d6540a9] received
{"otelSpanID": "0378e458ec61afbf", "otelTraceID": "04ea70c6d45335346fd93ae121433ce6", "otelTraceSampled": true, "otelServiceName": "unknown_service", "message": "no mib found 1.3.6.1.4.1.193.183.4.2.0.15 based on 1.3.6.1.4.1.193.183.4.2.0.15 from 10.11.251.35", "time": "2024-09-16T11:43:36.355835", "level": "WARNING"}
{"otelSpanID": "0378e458ec61afbf", "otelTraceID": "04ea70c6d45335346fd93ae121433ce6", "otelTraceSampled": true, "otelServiceName": "unknown_service", "message": "no mib found 0 based on 0 from 10.11.251.35", "time": "2024-09-16T11:43:36.357140", "level": "WARNING"}
{"otelSpanID": "0378e458ec61afbf", "otelTraceID": "04ea70c6d45335346fd93ae121433ce6", "otelTraceSampled": true, "otelServiceName": "unknown_service", "message": "no mib found 0.0 based on 0.0 from 10.11.251.35", "time": "2024-09-16T11:43:36.357994", "level": "WARNING"}
{"otelSpanID": "0378e458ec61afbf", "otelTraceID": "04ea70c6d45335346fd93ae121433ce6", "otelTraceSampled": true, "otelServiceName": "unknown_service", "message": "no mib found 1 based on 1 from 10.11.251.35", "time": "2024-09-16T11:43:36.359124", "level": "WARNING"}
{"otelSpanID": "0378e458ec61afbf", "otelTraceID": "04ea70c6d45335346fd93ae121433ce6", "otelTraceSampled": true, "otelServiceName": "unknown_service", "message": "no mib found 1.3.6.1.4.1.193.183.4.1.4.5.1.5 based on 1.3.6.1.4.1.193.183.4.1.4.5.1.5 from 10.11.251.35", "time": "2024-09-16T11:43:36.359776", "level": "WARNING"}
{"otelSpanID": "0378e458ec61afbf", "otelTraceID": "04ea70c6d45335346fd93ae121433ce6", "otelTraceSampled": true, "otelServiceName": "unknown_service", "message": "no mib found 1.3.6.1.4.1.193.183.4.1.4.5.1.2 based on 1.3.6.1.4.1.193.183.4.1.4.5.1.2 from 10.11.251.35", "time": "2024-09-16T11:43:36.359866", "level": "WARNING"}
{"otelSpanID": "0378e458ec61afbf", "otelTraceID": "04ea70c6d45335346fd93ae121433ce6", "otelTraceSampled": true, "otelServiceName": "unknown_service", "message": "no mib found 1.3.6.1.4.1.193.183.4.1.4.5.1.3 based on 1.3.6.1.4.1.193.183.4.1.4.5.1.3 from 10.11.251.35", "time": "2024-09-16T11:43:36.359922", "level": "WARNING"}
{"otelSpanID": "0378e458ec61afbf", "otelTraceID": "04ea70c6d45335346fd93ae121433ce6", "otelTraceSampled": true, "otelServiceName": "unknown_service", "message": "no mib found 1.3.6.1.4.1.193.183.4.1.4.5.1.11 based on 1.3.6.1.4.1.193.183.4.1.4.5.1.11 from 10.11.251.35", "time": "2024-09-16T11:43:36.359974", "level": "WARNING"}
{"otelSpanID": "0378e458ec61afbf", "otelTraceID": "04ea70c6d45335346fd93ae121433ce6", "otelTraceSampled": true, "otelServiceName": "unknown_service", "message": "no mib found 1.3.6.1.4.1.193.183.4.1.2.1 based on 1.3.6.1.4.1.193.183.4.1.2.1 from 10.11.251.35", "time": "2024-09-16T11:43:36.360049", "level": "WARNING"}
{"otelSpanID": "0378e458ec61afbf", "otelTraceID": "04ea70c6d45335346fd93ae121433ce6", "otelTraceSampled": true, "otelServiceName": "unknown_service", "message": "no mib found 1.3.6.1.4.1.193.183.4.1.2.7 based on 1.3.6.1.4.1.193.183.4.1.2.7 from 10.11.251.35", "time": "2024-09-16T11:43:36.360134", "level": "WARNING"}
{"otelSpanID": "0378e458ec61afbf", "otelTraceID": "04ea70c6d45335346fd93ae121433ce6", "otelTraceSampled": true, "otelServiceName": "unknown_service", "message": "no mib found 1.3.6.1.4.1.193.183.4.1.2.8 based on 1.3.6.1.4.1.193.183.4.1.2.8 from 10.11.251.35", "time": "2024-09-16T11:43:36.360196", "level": "WARNING"}
{"otelSpanID": "0378e458ec61afbf", "otelTraceID": "04ea70c6d45335346fd93ae121433ce6", "otelTraceSampled": true, "otelServiceName": "unknown_service", "message": "no mib found 1.3.6.1.4.1.193.183.4.1.2.9 based on 1.3.6.1.4.1.193.183.4.1.2.9 from 10.11.251.35", "time": "2024-09-16T11:43:36.360241", "level": "WARNING"}
````

The current configuration of the MIB server is:
````
mibserver:
  image:
    tag: "1.15.11"
````

And the status of pods apparently it's fine:

![image](https://github.com/user-attachments/assets/36649107-fe48-4916-9933-4ad9f86208d2)

Thanks you in advance.

**Comment by ajasnosz** [comment] 2024-09-18 06:40
Hello @ivanfr90,
the issue is fixed in version 1.15.13.

**Closed by ajasnosz** 2024-09-18 06:40 UTC

**Comment by ivanfr90** [comment] 2024-09-18 11:31
Hi @ajasnosz 

Thanks for your fast solution!! :)

We deployed the latest version of the MIB Server 1.15.13 and apparently it works well (data interpretation of MIBs its fine), but it's curious that the warning message continues showing in the worker logs:

![image](https://github.com/user-attachments/assets/10fa9e2e-6182-4666-b1a4-f9c0c93b011e)

Have you an idea of what its causing this warning?

thanks!

**Comment by ajasnosz** [comment] 2024-09-18 12:59
I think it might be wrong interpretation of incoming traps or the incoming data is incorrect. Is your notification agent sending some additional data for traps? As the numbers in those warnings should be actually oids that were not found in mibserver, but it is not really possible that they are just 1 digit. 
This looks like the issue in sc4snmp code rather than mibserver, so if you want us to take closer look you can open the issue on [sc4snmp repository](https://github.com/splunk/splunk-connect-for-snmp/issues).
